[snowflake]
user = "CAPTAINSEJ"
password = "!!Magyk/19"
account = "gyvuggx-rvb69315"
role = "OWNERSHIP"
warehouse = "COMPUTE_WH"
database = "STARKNET_DATA_WAREHOUSE__T1"
schema = "STARKNET"
client_session_keep_alive = true